package seed

import (
	"bytes"
	"errors"
	"fmt"
	"strings"
	"text/template"
)

// Render turns a Seed into its on-disk markdown form. Output is fully
// deterministic: no timestamps, no random ordering, no environment reads.
// Same Seed in, byte-identical bytes out, every time.
//
// The renderer enforces the "AI vs human" provenance boundary in markup:
//
//   - AI-authored content lives under Proposed Summary, Suggested Themes,
//     and Why It Might Matter.
//   - Human-authored content lives under Capture Why (if --why was given)
//     and Human Notes.
//
// A reviewer scanning the file should never be in doubt about who wrote
// any given line.
type renderView struct {
	ID               string
	Title            string
	SourceCSV        string   // for the frontmatter line
	Sources          []string // for the body list
	MultiSource      bool
	ProposedSummary  string
	SuggestedThemes  []string
	WhyItMightMatter string
	HasUserWhy       bool
	UserWhy          string
	HasLegacyPath    bool
	LegacyPath       string
}

// Template is intentionally laid out exactly as it appears on disk.
// Whitespace, blank lines, and trailing newline are part of the contract
// tested by the renderer tests.
const seedTemplate = `---
type: seed
status: open
generated_by: silo
source_observation: {{ .SourceCSV }}
---

# {{ .Title }}

## Proposed Summary

{{ .ProposedSummary }}

## Suggested Themes

{{ range .SuggestedThemes }}- {{ . }}
{{ end }}
## Why It Might Matter

{{ .WhyItMightMatter }}
{{ if .HasLegacyPath }}
## Source

- Legacy path: {{ .LegacyPath }}

{{ end }}
{{ if .HasUserWhy }}
## Capture Why

> {{ .UserWhy }}

(Written by the human at capture time. Not generated by Silo.)
{{ end }}
## Human Notes

TODO.
`

func Render(s Seed) (string, error) {
	if strings.TrimSpace(s.ID) == "" {
		return "", errors.New("seed ID is empty")
	}
	if len(s.SourceObservationIDs) == 0 {
		return "", errors.New("seed has no source observations")
	}

	view := renderView{
		ID:               s.ID,
		Title:            fallback(s.Title, "Untitled seed"),
		SourceCSV:        sourceCSV(s.SourceObservationIDs),
		Sources:          s.SourceObservationIDs,
		MultiSource:      len(s.SourceObservationIDs) > 1,
		ProposedSummary:  fallback(s.ProposedSummary, "(no summary)"),
		SuggestedThemes:  defaultThemes(s.SuggestedThemes),
		WhyItMightMatter: fallback(s.WhyItMightMatter, "(no contextualization)"),
		HasUserWhy:       strings.TrimSpace(s.UserWhy) != "",
		UserWhy:          strings.TrimSpace(s.UserWhy),
		HasLegacyPath:    strings.TrimSpace(s.LegacyPath) != "",
		LegacyPath:       strings.TrimSpace(s.LegacyPath),
	}

	tmpl, err := template.New("seed").Parse(seedTemplate)
	if err != nil {
		return "", fmt.Errorf("parse seed template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, view); err != nil {
		return "", fmt.Errorf("render seed %q: %w", s.ID, err)
	}
	return buf.String(), nil
}

// sourceCSV renders the frontmatter source_observation field. For a single
// observation we emit it bare ("obs-123") to match the spec example. For
// multiple sources we emit a YAML inline list ("[obs-a, obs-b]") so the
// frontmatter remains valid YAML in either case.
func sourceCSV(ids []string) string {
	if len(ids) == 1 {
		return ids[0]
	}
	return "[" + strings.Join(ids, ", ") + "]"
}

func fallback(s, def string) string {
	if strings.TrimSpace(s) == "" {
		return def
	}
	return s
}

func defaultThemes(themes []string) []string {
	if len(themes) == 0 {
		return []string{"unclassified"}
	}
	return themes
}
